version: "3"

services:
    accounts_db:
        image: postgres
        restart: always
        ports:
            - 5433:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: accounts