CREATE TABLE IF NOT EXISTS users(
   id SERIAL PRIMARY KEY NOT NULL,
   first_name VARCHAR (100) NOT NULL,
   last_name VARCHAR (100) NOT NULL,
   password VARCHAR (100) NOT NULL,
   email VARCHAR (300) UNIQUE NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);
